import pandas as pd
import streamlit as st
import plotly.express as px
df = pd.read_csv("supermarket_sales.csv")
st.set_page_config(page_title = "My Supermarket Sale Dashboard",page_icon=":bar_chart:",layout="wide")
st.sidebar.header("Please filter here")
pchoice = st.sidebar.multiselect("Select Product",options = df["Product line"].unique(),default = df["Product line"].unique()[:6])
cchoice = st.sidebar.multiselect("Select City",options = df["City"].unique(),default = df["City"].unique()[:3])
dchoice = st.sidebar.multiselect("Select Date",options = df["Date"].unique(),default = df["Date"].unique()[:10])
st.title(":bar_chart: Supermarket Sales Dashboard for 2025")
ourtotal = df["Total"].sum()
no_of_product = df["Product line"].nunique()
left,right = st.columns(2)
with left:
    st.subheader("Total Sale")
    st.subheader(f"US $ {ourtotal}")
with right:
    st.subheader("No. of Product")
    st.subheader(f"{no_of_product}")
df_select = df.query("`Product line` == @pchoice and City == @cchoice and Date == @dchoice")
pp = df_select.groupby("Product line")["Total"].sum().sort_values()
fig_by_Product = px.bar(pp,x=pp.values,y=pp.index,title="Total Sale by Product")
dd = df_select.groupby("Date")["Total"].sum().sort_values()
fig_by_Date = px.bar(dd,x=dd.values,y=dd.index,title="Total Sale by Date")
fig_by_pie = px.pie(df_select,values="Total",names="City",title="Total Sale by Date")
a,b,c = st.columns(3)
a.plotly_chart(fig_by_Product,use_container_width = True)
c.plotly_chart(fig_by_Date,use_container_width = True)
b.plotly_chart(fig_by_pie,use_container_width = True)
fig_line = px.line(dd,x=dd.values,y=dd.index,title="Total Sale by Date")
fig_scatter = px.scatter(df_select, x="Total", y="Quantity", title="Total Sale by Quantity")
d,e=st.columns(2)
d.plotly_chart(fig_line,use_container_width=True)
e.plotly_chart(fig_scatter,use_container_width=True)
